---
title: "sample"
author: "Hamid Khan"
date: "3/5/2020"
output: html_document
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)

library(googlesheets4)

library(janitor)
library(purrr)
library(tibble)
library(stringr)
library(forcats)

sheets_deauth()

```

```{r plot set-up, include = F}

x <- 
  
  read_sheet(
    
    "14HmwN2cEVAJHupuehCuLdwG9BXtR3COrxDgaaylLhkA") %>%
             
  clean_names("snake") %>%
  
  arrange(desc(red)) %>%
  
  mutate(percent_red = red/(red+white))

```

```{r plot, echo= FALSE}

 plot <- 
   
   x %>% 
  
  ggplot(aes(percent_red)) +
  
  geom_histogram(bins=20) +
  
  labs(title = "Percent of Red Drawn from a Sample of 25",
       subtitle = "Drawn Randomly",
       xtitle = "Percentage of Red Beads Drawn out of 25",
       ytitle = "Frequency")
 
 plot



```


```{r function, include =F}

xt <- tibble(bean_id = 1:1000,
       
       color = c(rep("Red", 200), 
                 
                 rep("White", 800)))



shovel <- function(n) {
    sample_n(xt, n, replace = TRUE)
}

t <- shovel(10)

virtual_shovel <- shovel(25) %>%
    summarize(sum(color =="Red")/sum(n()))

newxt <- xt %>%
  sample_n(size = 25, reps = 51)%>%
  mutate(red_sum = sum(color == "Red"))%>%
  mutate(perc_red = red_sum / 25)

# fell off after this point. 

sim_results <- tibble(sim_ID = 1:3, 
                      )
xttibble <- tibble()






```

